#!/usr/bin/env python3
"""Measure an RMS-generated map exactly, by reading a scenario export.

Dev-side verification tool, never invoked by the shipped app. It exists because
eyeballing screenshots cannot count: the Phase 4.1 in-game verification pass
(docs/preview-design.md Sec.15) settled the questions with binary observables
("is the gold on the dirt or not") and could not touch the ones needing a
number, such as whether a scaled tile budget comes out at 829 or 840.

WORKFLOW
    1. In DE's scenario editor: pick the RMS under "Random Map location",
       Generate Map, then Save As a scenario.
    2. Run this against the saved file. Default scenario folder is
       %USERPROFILE%\\Games\\Age of Empires 2 DE\\<steamid>\\resources\\_common\\scenario
    3. Compare the printed counts against what the script asked for.

Because the map is generated by the real engine and then measured exactly, this
is the only instrument in the project that can calibrate the [tune] constants
against ground truth rather than against the guide's prose.

SETUP
    pip install -r requirements.txt

WINDOWS GOTCHA
    AoE2ScenarioParser prints emoji progress markers. On a cp1252 console that
    raises UnicodeEncodeError *during parsing*, which looks like a parse failure
    and is not. This script forces UTF-8 on stdout at import time, so it works
    under a bare `python probe_scenario.py`. If you call the library yourself,
    set PYTHONIOENCODING=utf-8.
"""

from __future__ import annotations

import argparse
import io
import json
import math
import sys
from collections import Counter
from pathlib import Path

# Must happen before AoE2ScenarioParser prints anything. See WINDOWS GOTCHA.
if hasattr(sys.stdout, "buffer"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[2]
GAME_CONSTANTS = REPO_ROOT / "reference" / "data" / "game-constants.json"


def load_constant_names() -> tuple[dict[int, str], dict[int, str]]:
    """constId -> RMS constant name, split by category.

    Read from our own extracted reference data, which doubles as a cross-check:
    the scenario file and random_map.def are entirely separate code paths, so
    agreement between them is real corroboration of the Phase 4.0 extraction.
    Unknown ids print as bare numbers rather than guesses.
    """
    if not GAME_CONSTANTS.is_file():
        return {}, {}
    data = json.loads(GAME_CONSTANTS.read_text(encoding="utf-8"))
    terrains, objects = {}, {}
    for c in data.get("constants", []):
        cid = c.get("constId")
        if cid is None:
            continue
        (terrains if c.get("category") == "terrain" else objects)[cid] = c["rmsConstant"]
    return terrains, objects


def name_for(lookup: dict[int, str], cid: int) -> str:
    return f"{lookup.get(cid, '?')} ({cid})" if cid in lookup else f"id {cid}"


def report_bbox(tiles, terrain_names: dict[int, str], want: str, dim: int) -> None:
    """Bounding box of one terrain, for measuring where a bordered land stops.

    Counts cannot answer border questions — Sec.4's floor-low-edge /
    ceil-high-edge rule differs from its rivals by a single tile per edge, so
    the observable is a *position*. Reported as both the tile index and the
    inset from each map edge, because border attributes are specified as an
    inset and comparing them directly is what avoids off-by-one mistakes.
    """
    # Skip unnamed rows. Reference data is a POSITIVE resolver: a row can
    # legitimately carry a null constant name (most of the 131 terrains have no
    # callable constant), and an unnamed row must make this lookup smaller,
    # never raise. Without the guard every --bbox/--patches/--clusters read
    # crashed on any map containing one.
    lookup = {name.upper(): cid for cid, name in terrain_names.items() if name}
    tid = lookup.get(want.upper())
    if tid is None:
        try:
            tid = int(want)
        except ValueError:
            print(f"\n--- bbox: unknown terrain {want!r} (known: {', '.join(sorted(lookup))}) ---")
            return

    xs = [t.x for t in tiles if t.terrain_id == tid]
    ys = [t.y for t in tiles if t.terrain_id == tid]
    label = name_for(terrain_names, tid)
    if not xs:
        print(f"\n--- bbox {label}: not present ---")
        return

    print(f"\n--- bbox {label} ({len(xs)} tiles, map 0..{dim - 1}) ---")
    print(f"  x: {min(xs)}..{max(xs)}   inset  left={min(xs)}  right={dim - 1 - max(xs)}")
    print(f"  y: {min(ys)}..{max(ys)}   inset  top={min(ys)}   bottom={dim - 1 - max(ys)}")
    print("  (left/top are the low-index edges, right/bottom the high-index ones — Sec.4)")


def connected_components(pts: set, diagonal: bool) -> list[list]:
    """Flood-fill `pts` into components. `diagonal` picks 8- vs 4-connectivity.

    Both callers use **4**, and the reason is the same for each: it is a claim
    about how the thing under measurement was built, not a preference.

    - Terrain (`--patches`). Sec.6.1/6.4 grow a clump by sampling candidates
      *4-adjacent* to owned tiles, so an engine-grown clump is 4-connected by
      construction.
    - Objects (`--clusters`). A tight group's fill is also strictly 4-connected.
      **MEASURED, RMSTEST_26**: 300 declared groups of 5 gold came back as
      exactly 300 components of exactly 5 under 4-connectivity. The engine never
      takes a diagonal step during a fill.

    This function used to pass `diagonal=True` for objects, on the reasoning
    that an unchecked fill (Sec.15 item 10) meant a diagonal touch was still one
    group. The premise was right and the conclusion did not follow: the fill
    being unconstrained by *attributes* says nothing about its *adjacency* rule.
    On the same RMSTEST_26 data, 8-connectivity returned 299 components with one
    blob of 10 — two distinct groups that happened to touch at a corner, merged
    into a single wrong reading. That is the exact failure this docstring used to
    claim was impossible.

    Effect on the one result that depended on it: RMSTEST_18 (Sec.15 item 10)
    measured a minimum inter-group gap of 8 against a declared 12. A merge can
    only *drop* a pair from the gap matrix, never invent a smaller gap, so the
    true minimum is at most the 8 that was reported and the refutation of
    per-member enforcement holds a fortiori.
    """
    offsets = [(dx, dy)
               for dx in (-1, 0, 1)
               for dy in (-1, 0, 1)
               if (dx, dy) != (0, 0) and (diagonal or dx == 0 or dy == 0)]
    seen: set = set()
    out: list[list] = []
    for start in pts:
        if start in seen:
            continue
        stack, comp = [start], []
        seen.add(start)
        while stack:
            x, y = stack.pop()
            comp.append((x, y))
            for dx, dy in offsets:
                n = (x + dx, y + dy)
                if n in pts and n not in seen:
                    seen.add(n)
                    stack.append(n)
        out.append(comp)
    return out


def resolve_terrain(terrain_names: dict[int, str], want: str) -> int | None:
    # Skip unnamed rows. Reference data is a POSITIVE resolver: a row can
    # legitimately carry a null constant name (most of the 131 terrains have no
    # callable constant), and an unnamed row must make this lookup smaller,
    # never raise. Without the guard every --bbox/--patches/--clusters read
    # crashed on any map containing one.
    lookup = {name.upper(): cid for cid, name in terrain_names.items() if name}
    tid = lookup.get(want.upper())
    if tid is not None:
        return tid
    try:
        return int(want)
    except ValueError:
        print(f"\n--- unknown terrain {want!r} (known: {', '.join(sorted(lookup))}) ---")
        return None


def report_patches(tiles, terrain_names: dict[int, str], want: str) -> None:
    """Per-clump shape and position for one terrain — the item 2 and 3 instrument.

    Two open calibration questions reduce to numbers this prints:

    - **Item 2, the cross-shaped land area.** Place many single-tile lands of one
      terrain with no `land_position`; each patch is then one *origin*, and the
      centroid list is the origin scatter. The corner exclusion falls out of the
      coordinates instead of being eyeballed off a screenshot.
    - **Item 3, growth-frontier weight buckets.** `circularity` is
      `4*pi*area / perimeter**2`, normalised so a disc is 1.0 and a one-tile-wide
      snake tends to 0. That is the scale-free version of "snakey versus round",
      so patches grown at different `clumping_factor` values are comparable even
      when their budgets differ. Guide:927's regimes predict an ordering, and an
      ordering is a falsifiable claim.

    `math` is used freely here on purpose. Sec.8's ban on `Math.pow` governs the
    shipped simulator, where float drift would break seeded reproducibility; this
    is a dev-side measurement of a map the engine already finished making.
    """
    tid = resolve_terrain(terrain_names, want)
    if tid is None:
        return
    label = name_for(terrain_names, tid)
    pts = {(t.x, t.y) for t in tiles if t.terrain_id == tid}
    if not pts:
        print(f"\n--- patches {label}: not present ---")
        return

    patches = connected_components(pts, diagonal=False)
    patches.sort(key=len, reverse=True)
    print(f"\n--- patches {label}: {len(patches)} patch(es), {len(pts)} tiles (4-connectivity) ---")
    print("     n      cx      cy   bbox w x h   perim   circularity")
    for p in patches:
        area = len(p)
        owned = set(p)
        perim = sum(1
                    for x, y in p
                    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                    if (x + dx, y + dy) not in owned)
        xs = [x for x, _ in p]
        ys = [y for _, y in p]
        circ = (4 * math.pi * area) / (perim * perim) if perim else float("nan")
        print(f"  {area:>4}  {sum(xs) / area:>6.1f}  {sum(ys) / area:>6.1f}   "
              f"{max(xs) - min(xs) + 1:>3} x {max(ys) - min(ys) + 1:<3}  "
              f"{perim:>6}   {circ:>6.3f}")

    if len(patches) > 1:
        areas = [len(p) for p in patches]
        print(f"  totals: mean area {sum(areas) / len(areas):.1f}, "
              f"largest {max(areas)}, smallest {min(areas)}")


def report_rows(tiles, terrain_names: dict[int, str], want: str, dim: int, bands: int) -> None:
    """Where a feature sits along each axis, as a banded histogram plus a mean.

    Built for two item 1 constants whose observable is a *distribution*, not a
    count:

    - **Elevation's south bias** (Sec.6.2). Pass `ELEVATION` and the tile set is
      every tile above level 0. The single number that decides it is `mean y`,
      printed as a fraction of the map. Under integer weight `100 + 100*y/(dim-1)`
      the expected fraction is **0.556**; under `enable_balanced_elevation`'s
      `100 + 15*y/(dim-1)` it is **0.512**; a uniform seed pick gives **0.500**.
      Those three predictions are far enough apart to separate on a few hundred
      clumps, which is the whole reason the constant is stated as integer weights.
    - **`border_fuzziness` penetration** (Sec.6.1). The band counts beyond a
      declared border are the depth profile, and the spec claims it decays
      geometrically rather than as a flat coin-flip.

    `mean x` is printed as the control. Neither mechanism is supposed to bias the
    x axis, so an x mean that drifts off 0.500 means the run is measuring
    something other than what it thinks it is.
    """
    if want.upper() == "ELEVATION":
        pts = [(t.x, t.y) for t in tiles if t.elevation > 0]
        label = "elevation > 0"
    else:
        tid = resolve_terrain(terrain_names, want)
        if tid is None:
            return
        pts = [(t.x, t.y) for t in tiles if t.terrain_id == tid]
        label = name_for(terrain_names, tid)
    if not pts:
        print(f"\n--- rows {label}: not present ---")
        return

    n = len(pts)
    width = max(1, dim // bands)
    rows: Counter[int] = Counter()
    cols: Counter[int] = Counter()
    for x, y in pts:
        cols[min(bands - 1, int(x) // width)] += 1
        rows[min(bands - 1, int(y) // width)] += 1

    print(f"\n--- rows {label}: {n} tiles, {bands} bands of {width} on a {dim} map ---")
    print("  band   y range        by row            by column")
    for b in range(bands):
        lo = b * width
        hi = min(dim, lo + width) - 1
        r, c = rows[b], cols[b]
        print(f"  {b:>4}   {lo:>3}..{hi:<3}   {r:>7} {'#' * min(40, r * 40 // max(1, max(rows.values()))):<40} {c:>7}")

    mean_y = sum(y for _, y in pts) / n / max(1, dim - 1)
    mean_x = sum(x for x, _ in pts) / n / max(1, dim - 1)
    print(f"  mean y = {mean_y:.4f} of map   (uniform 0.500, spec south bias 0.556, spec balanced 0.512)")
    print(f"  mean x = {mean_x:.4f} of map   (control — should sit at 0.500)")


def report_clusters(units, object_names: dict[int, str], want: str) -> None:
    """Spatial clusters of one object type, and the gaps between them.

    Group membership is NOT stored in the scenario file, but a tight group is
    contiguous by definition, so connected components recover the groups. That
    makes questions about *inter-group* spacing measurable — e.g. whether
    min_distance_group_placement is enforced once per group or per member,
    which shows up as the gap between blob edges.

    Uses 8-connectivity to build clusters (a group touching only diagonally is
    still one group) and reports the gap in Chebyshev distance, since the
    engine's distance constraints are square by default (guide:2652).
    """
    # See the note in report_bbox: an unnamed row must shrink the lookup, not
    # raise. Objects hit this more often than terrains do.
    lookup = {name.upper(): cid for cid, name in object_names.items() if name}
    cid = lookup.get(want.upper())
    if cid is None:
        try:
            cid = int(want)
        except ValueError:
            print(f"\n--- clusters: unknown object {want!r} ---")
            return

    pts = {(u.x, u.y) for u in units if u.unit_const == cid}
    label = name_for(object_names, cid)
    if not pts:
        print(f"\n--- clusters {label}: none present ---")
        return

    # Unit coordinates are floats (objects sit at tile centres) while the
    # neighbour walk steps by integer 1, so adjacency only resolves while every
    # instance shares one fractional offset. Filtering to a single unit_const is
    # what makes that hold. If it ever stops holding the failure is silent and
    # reads as a real result — every object becomes its own blob, and "49 blobs
    # of 1" looks like 49 groups rather than like a broken measurement.
    fractions = {(round(x % 1, 3), round(y % 1, 3)) for x, y in pts}
    if len(fractions) > 1:
        print(f"\n!! {label}: mixed tile offsets {sorted(fractions)} — blob counts below are meaningless")

    clusters = connected_components(pts, diagonal=False)
    clusters.sort(key=len, reverse=True)
    print(f"\n--- clusters {label}: {len(clusters)} blob(s), {len(pts)} objects (4-connectivity) ---")
    print("  sizes: " + ", ".join(str(len(c)) for c in clusters))

    if len(clusters) < 2:
        print("  only one blob — nothing to measure between groups")
        return

    gaps = []
    for i in range(len(clusters)):
        for j in range(i + 1, len(clusters)):
            d = min(max(abs(ax - bx), abs(ay - by)) for ax, ay in clusters[i] for bx, by in clusters[j])
            gaps.append((d, i, j))
    gaps.sort()
    print(f"  minimum edge-to-edge gap (Chebyshev): {gaps[0][0]}")
    print("  all pairwise gaps: " + ", ".join(str(g[0]) for g in gaps))


def probe(
    path: Path,
    top: int,
    bbox: str | None = None,
    clusters: str | None = None,
    patches: str | None = None,
    rows: str | None = None,
    bands: int = 10,
) -> None:
    from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario

    scenario = AoE2DEScenario.from_file(str(path))
    terrain_names, object_names = load_constant_names()

    mm = scenario.map_manager
    tiles = list(mm.terrain)
    terrain_counts: Counter[int] = Counter()
    elevation_counts: Counter[int] = Counter()
    for tile in tiles:
        terrain_counts[tile.terrain_id] += 1
        elevation_counts[tile.elevation] += 1

    print(f"\n=== MAP: {path.name} ===")
    print(f"map_size {mm.map_size} -> {mm.map_size ** 2} tiles; parsed {len(tiles)}")
    if len(tiles) != mm.map_size ** 2:
        print("  !! tile count does not match map_size squared — read the parse output above")

    print("\n--- terrain ---")
    for cid, n in terrain_counts.most_common(top):
        print(f"  {n:>7}  {name_for(terrain_names, cid)}")

    print("\n--- elevation ---")
    for level, n in sorted(elevation_counts.items()):
        print(f"  {n:>7}  level {level}")

    if bbox:
        report_bbox(tiles, terrain_names, bbox, mm.map_size)
    if patches:
        report_patches(tiles, terrain_names, patches)
    if rows:
        report_rows(tiles, terrain_names, rows, mm.map_size, bands)

    units = scenario.unit_manager.get_all_units()
    if clusters:
        report_clusters(units, object_names, clusters)
    print(f"\n--- objects ({len(units)} total) ---")
    for cid, n in Counter(u.unit_const for u in units).most_common(top):
        print(f"  {n:>7}  {name_for(object_names, cid)}")

    print(
        "\nNote: forest terrain auto-places tree objects, so a forest-heavy map shows\n"
        "tens of thousands of units. Filter by constant when that is noise."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("scenario", type=Path, help="Path to a .aoe2scenario file")
    parser.add_argument("--top", type=int, default=12, help="How many entries per histogram (default 12)")
    parser.add_argument("--bbox", default=None, metavar="TERRAIN",
                        help="Also report the bounding box and per-edge inset of one terrain, "
                             "by RMS constant name (GRASS) or numeric id. Needed for border tests.")
    parser.add_argument("--clusters", default=None, metavar="OBJECT",
                        help="Group one object type into contiguous blobs and report the gaps "
                             "between them. Recovers tight groups, whose membership the scenario "
                             "file does not store. Needed for group-spacing tests.")
    parser.add_argument("--patches", default=None, metavar="TERRAIN",
                        help="Split one terrain into 4-connected patches and report each patch's "
                             "area, centroid, bounding box and circularity. Centroids answer the "
                             "cross-shape question (Sec.15 item 2); circularity answers the "
                             "clumping-factor regimes (item 3).")
    parser.add_argument("--rows", default=None, metavar="TERRAIN|ELEVATION",
                        help="Banded row/column histogram plus the mean position on each axis. "
                             "Pass ELEVATION for every tile above level 0. Needed for elevation's "
                             "south bias and for border_fuzziness penetration depth (item 1).")
    parser.add_argument("--bands", type=int, default=10, help="Bands for --rows (default 10)")
    args = parser.parse_args()

    if not args.scenario.is_file():
        print(f"not found: {args.scenario}", file=sys.stderr)
        return 1
    probe(args.scenario, args.top, args.bbox, args.clusters, args.patches, args.rows, args.bands)
    return 0


if __name__ == "__main__":
    sys.exit(main())
